apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      serviceAccountName: api-service-account
      containers:
      - name: api-server
        image: factory-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: AAS_SERVER_URL
          value: "http://aas-mock-service:5001"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-server
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer